version: '3.4'

services:
  mybudget:
    image: ${DOCKER_REGISTRY-}mybudget
    build:
      context: .
      dockerfile: MyBudget/Dockerfile
    depends_on:
      - mybudgetdb

  mybudgetdb:
   image: mcr.microsoft.com/mssql/server:2019-latest
   ports:
     - 1433:1433 
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=password@12345#

volumes:
  myapp_logsvolume:
